
class ChangeEntry
  include Ripple::EmbeddedDocument

  timestamps!

  property :action, String, :presence => true
  property :resume, Array, :presence => true, :default => []

  property :difference_key, String, :presence => true
  one :difference, :using => :stored_key, :class_name => "Difference"

  # Author, and cached data
  property :author_key, String, :presence => true, :index => true
  property :author_nick, String, :presence => true
  property :author_hash, String, :presence => true
  one :author, :using => :stored_key, :class_name => "User"


  def self.create_new(action, author, object)
    diff = Difference.create_new(object)
    entry = self.new({
      :author_key => author.id,
      :author_nick => author.nick,
      :author_hash => author[:hash],
      :difference_key => diff.key,
      :action => action
    })
    diff.old.each do |prop, old_value|
      entry.resume << prop
    end
    entry
  end
end

class Difference
  include Ripple::Document

  property :id, String
  key_on :id
  timestamps!

  property :old, Hash, :default => {}
  property :new, Hash, :default => {}
  property :current, Hash

  def self.create_new(object)
    diff = self.new
    diff.current = {
      :bucket => object.robject.bucket.name,
      :key => object.robject.key
    }

    object.changes.each do |prop, values|
      next if object.class.are_safe && !object.class.are_safe[prop]
      diff.old[prop] = values[0]
      diff.new[prop] = values[1]
    end
    diff.save!
    diff.save # save autogenerated ID (fixme)
    diff
  end
end
